name: Ruby

on:
  push:
    branches:
      - main
      - feature/fix-ci

env:
  VERSION_ID: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6'
        bundler-cache: true

    - name: compress zip
      run: |
        zip costNotifierRuby lambda_function.rb -r vendor

    - name: Deploy Lambda
      env:
        ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: ${{ secrets.AWS_REGION }}
      run: |
        gem install aws-sdk-lambda
        ruby ./deploy/deploy_lambda.rb
