name: Deploy Lambda

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6'
        bundler-cache: true

    - name: Run Rubocop
      run: bundle exec rubocop

    - name: compress zip
      if: github.ref == 'refs/heads/main'
      run: |
        zip -r costNotifierRuby lambda_function.rb vendor

    - name: Configure AWS Credentials
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: RubyCostNotifier
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy Lambda
      if: github.ref == 'refs/heads/main'
      env:
        REGION: ${{ secrets.AWS_REGION }}
      run: |
        gem install aws-sdk-lambda
        ruby ./deploy/deploy_lambda.rb

    - name: Send Result to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }